<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Mayden Shopping List</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="css/style.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1>Mayden Shopping List</h1>
        <div></div>
        <form class="addItem" method="post" action="addItem.php">
            <input class="newItem" type="text" name="item">
            <input type="submit" value="Add Item">
        </form>

<!--        --><?php //if (isset($name)) : ?>
<!--            <h2>Hello --><?//= htmlspecialchars($name); ?><!--!</h2>-->
<!--        --><?php //else: ?>
<!--            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>-->
<!--        --><?php //endif; ?>
    </body>
</html>
